package dataconv

import (
	"bytes"
	"encoding/json"
	"fmt"
	"math"
	"os"
	"path/filepath"
	"runtime"
	"slices"
	"sort"
	"strconv"
	"strings"
	"sync"
	"sync/atomic"

	"github.com/Fokiiiiiii/amagi-data/azurlanelua"
)

const globalDir = "global"

var supportedRegions = []string{"CN", "EN", "JP", "KR", "TW"}

type Options struct {
	SourceRoot     string
	OutputRoot     string
	ReportPath     string
	LuaScriptsRoot string
	ConstantsRoot  string
}

type Report struct {
	SourceRoot              string             `json:"source_root"`
	OutputRoot              string             `json:"output_root"`
	Regions                 []string           `json:"regions"`
	Categories              []string           `json:"categories"`
	GeneratedFiles          []string           `json:"generated_files"`
	GeneratedHelperFiles    []string           `json:"generated_helper_files"`
	UnsupportedFiles        []string           `json:"unsupported_files"`
	UnsupportedHelperFiles  []string           `json:"unsupported_helper_files"`
	MissingSourceFiles      []string           `json:"missing_source_files"`
	MissingReferenceFiles   []string           `json:"missing_reference_files"`
	SkippedUnsafeFiles      []string           `json:"skipped_unsafe_files"`
	GeneratedVersions       bool               `json:"generated_versions"`
	LuaScriptsVersionsRoot  string             `json:"lua_scripts_versions_root,omitempty"`
	LuaScriptsVersionSource map[string]string  `json:"lua_scripts_version_source,omitempty"`
	TotalGeneratedCount     int                `json:"total_generated_count"`
	TotalUnsupportedCount   int                `json:"total_unsupported_count"`
	CategoryCounts          map[string]int     `json:"category_counts,omitempty"`
	CategoryIDs             map[string][]int64 `json:"category_ids,omitempty"`
}

func loadLuaFile(opts Options, path string) (any, error) {
	if opts.ConstantsRoot == "" {
		return azurlanelua.LoadFile(path)
	}
	return azurlanelua.LoadFileWithConstantsRoot(path, opts.ConstantsRoot)
}

func newReport(opts Options) *Report {
	return &Report{
		SourceRoot:             opts.SourceRoot,
		OutputRoot:             opts.OutputRoot,
		Regions:                slices.Clone(supportedRegions),
		Categories:             []string{"GameCfg", "ShareCfg", "sharecfgdata", "root-helpers"},
		GeneratedFiles:         []string{},
		GeneratedHelperFiles:   []string{},
		UnsupportedFiles:       []string{},
		UnsupportedHelperFiles: []string{},
		MissingSourceFiles:     []string{},
		MissingReferenceFiles:  []string{},
		SkippedUnsafeFiles:     []string{},
	}
}

func ConvertMVP(opts Options) (*Report, error) {
	if opts.LuaScriptsRoot == "" {
		return nil, fmt.Errorf("Lua scripts root is required")
	}
	if opts.OutputRoot == "" {
		return nil, fmt.Errorf("output root is required")
	}

	report := newReport(opts)
	if err := generateDiscoveredLuaFiles(opts, report); err != nil {
		return nil, err
	}
	versions, source, err := generateVersionsJSON(opts.LuaScriptsRoot)
	if err != nil {
		return nil, err
	}
	outPath := filepath.Join(opts.OutputRoot, filepath.FromSlash(globalVersionsPath()))
	if err := writeVersionsJSON(outPath, versions); err != nil {
		return nil, err
	}
	report.GeneratedHelperFiles = append(report.GeneratedHelperFiles, globalVersionsPath())
	report.GeneratedVersions = true
	report.LuaScriptsVersionsRoot = source
	report.LuaScriptsVersionSource = versions
	if err := generateAdditionalLuaFiles(opts, report); err != nil {
		return nil, err
	}
	if err := writeReport(opts, report); err != nil {
		return nil, err
	}
	return report, nil
}

func generateDiscoveredLuaFiles(opts Options, report *Report) error {
	report.CategoryCounts = map[string]int{}
	report.CategoryIDs = map[string][]int64{}
	// sharecfgdata is converted first, as a whole pass, so every backing output exists
	// before a sharecfg stream facade (__stream__ = true) looks for it; the facade then
	// republishes those bytes instead of parsing the same multi-MB Lua source again.
	// Within a pass files convert concurrently, but results merge in walk order so the
	// report and the generated bytes match a sequential run exactly.
	backed := map[string]streamBackedOutput{}
	for _, dir := range []string{"sharecfgdata", "sharecfg"} {
		work, err := discoverLuaWork(opts, dir)
		if err != nil {
			return err
		}
		results, err := convertDiscoveredConcurrently(opts, work, backed)
		if err != nil {
			return err
		}
		for i, res := range results {
			if res == nil {
				continue
			}
			if res.unsupported {
				report.UnsupportedFiles = append(report.UnsupportedFiles, res.rel)
				report.TotalUnsupportedCount++
				continue
			}
			recordDiscoveredOutput(report, res.rel, res.dir, res.records, res.ids)
			if dir == "sharecfgdata" {
				backed[streamBackingKey(work[i].region, work[i].name)] = streamBackedOutput{
					path: res.outPath, records: res.records, ids: res.ids,
				}
			}
		}
	}
	sortStrings(report.GeneratedFiles)
	sortStrings(report.UnsupportedFiles)
	for key := range report.CategoryIDs {
		sort.Slice(report.CategoryIDs[key], func(i, j int) bool { return report.CategoryIDs[key][i] < report.CategoryIDs[key][j] })
		report.CategoryIDs[key] = slices.Compact(report.CategoryIDs[key])
	}
	return nil
}

type discoveredWork struct {
	region string
	dir    string
	name   string
}

func discoverLuaWork(opts Options, dir string) ([]discoveredWork, error) {
	var work []discoveredWork
	for _, region := range supportedRegions {
		root := filepath.Join(opts.LuaScriptsRoot, region, dir)
		if _, err := os.Stat(root); err != nil {
			continue
		}
		err := filepath.WalkDir(root, func(path string, entry os.DirEntry, walkErr error) error {
			if walkErr != nil {
				return walkErr
			}
			if entry.IsDir() || strings.Contains(filepath.ToSlash(path), "/sublist/") || !strings.HasSuffix(entry.Name(), ".lua") {
				return nil
			}
			work = append(work, discoveredWork{region: region, dir: dir, name: entry.Name()})
			return nil
		})
		if err != nil {
			return nil, err
		}
	}
	return work, nil
}

// runConcurrent applies fn to each index with a bounded worker pool and returns the
// results in index order. Callers merge those results sequentially, so concurrency
// never affects the report contents or the generated bytes.
func runConcurrent[T any](n int, fn func(int) (T, error)) ([]T, error) {
	results := make([]T, n)
	if n == 0 {
		return results, nil
	}
	var (
		wg       sync.WaitGroup
		cursor   atomic.Int64
		errOnce  sync.Once
		firstErr error
	)
	// GOMAXPROCS rather than NumCPU: it respects the CPU quota a CI container is
	// given, where NumCPU reports the host's cores and would oversubscribe.
	for range min(runtime.GOMAXPROCS(0), n) {
		wg.Add(1)
		go func() {
			defer wg.Done()
			for {
				i := int(cursor.Add(1)) - 1
				if i >= n {
					return
				}
				res, err := fn(i)
				if err != nil {
					errOnce.Do(func() { firstErr = err })
					return
				}
				results[i] = res
			}
		}()
	}
	wg.Wait()
	return results, firstErr
}

// convertDiscoveredConcurrently converts every item with a worker pool and returns
// results indexed by the original walk position, so callers can merge deterministically.
// backed is read-only here: it is fully populated by the preceding sharecfgdata pass.
func convertDiscoveredConcurrently(opts Options, work []discoveredWork, backed map[string]streamBackedOutput) ([]*discoveredResult, error) {
	return runConcurrent(len(work), func(i int) (*discoveredResult, error) {
		return convertDiscoveredLuaFile(opts, work[i], backed)
	})
}

// streamBackedOutput is the result of converting a sharecfgdata Lua file, kept so
// that the matching sharecfg stream facade can publish the identical bytes without
// re-parsing the backing source.
type streamBackedOutput struct {
	path    string
	records int
	ids     []int64
}

// discoveredResult is one converted file's contribution to the report, produced
// without touching shared state so conversions can run concurrently.
type discoveredResult struct {
	rel         string
	dir         string
	records     int
	ids         []int64
	outPath     string
	unsupported bool
}

func streamBackingKey(region, name string) string { return region + "/" + name }

// generateDiscoveredLuaFile converts one file and folds the result into the report.
// Used by the incremental path, which converts a handful of files sequentially.
func generateDiscoveredLuaFile(opts Options, report *Report, region, dir, name string, backed map[string]streamBackedOutput) error {
	res, err := convertDiscoveredLuaFile(opts, discoveredWork{region: region, dir: dir, name: name}, backed)
	if err != nil || res == nil {
		return err
	}
	if res.unsupported {
		report.UnsupportedFiles = append(report.UnsupportedFiles, res.rel)
		report.TotalUnsupportedCount++
		return nil
	}
	recordDiscoveredOutput(report, res.rel, res.dir, res.records, res.ids)
	if dir == "sharecfgdata" {
		backed[streamBackingKey(region, name)] = streamBackedOutput{path: res.outPath, records: res.records, ids: res.ids}
	}
	return nil
}

func convertDiscoveredLuaFile(opts Options, work discoveredWork, backed map[string]streamBackedOutput) (*discoveredResult, error) {
	region, dir, name := work.region, work.dir, work.name
	path := filepath.Join(opts.LuaScriptsRoot, region, dir, name)
	entry, err := os.Stat(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, err
	}
	if entry.IsDir() || strings.Contains(filepath.ToSlash(path), "/sublist/") || !strings.HasSuffix(name, ".lua") {
		return nil, nil
	}
	relDir := map[string]string{"sharecfg": "ShareCfg", "sharecfgdata": "sharecfgdata"}[dir]
	rel := region + "/" + relDir + "/" + strings.TrimSuffix(name, ".lua") + ".json"
	outPath := filepath.Join(opts.OutputRoot, filepath.FromSlash(rel))
	value, err := loadLuaFile(opts, path)
	if err != nil {
		if strings.Contains(rel, "/word_template_") || strings.Contains(rel, "/word_legal_template_") {
			return nil, nil
		}
		return &discoveredResult{rel: rel, dir: dir, unsupported: true}, nil
	}
	converted := azurlanelua.ToPlain(value)
	if backingPath, resolveErr := streamBackingPath(opts.LuaScriptsRoot, region, dir, name, converted); resolveErr != nil {
		return nil, resolveErr
	} else if backingPath != "" {
		if prior, ok := backed[streamBackingKey(region, name)]; ok {
			if err := copyGeneratedJSON(prior.path, outPath); err != nil {
				return nil, err
			}
			return &discoveredResult{rel: rel, dir: dir, records: prior.records, ids: prior.ids, outPath: outPath}, nil
		}
		value, err = loadLuaFile(opts, backingPath)
		if err != nil {
			return nil, err
		}
		converted = azurlanelua.ToPlain(value)
	}
	converted = normalizeNumericTables(converted)
	rawConverted := normalizeEmpty(converted)
	converted, err = dictKeyedToSortedList(rawConverted)
	if err != nil {
		converted = rawConverted
	}
	if err := writeJSON(outPath, converted); err != nil {
		return nil, err
	}
	return &discoveredResult{
		rel: rel, dir: dir, records: recordCount(converted), ids: comparableIDs(converted), outPath: outPath,
	}, nil
}

func recordDiscoveredOutput(report *Report, rel, dir string, records int, ids []int64) {
	report.GeneratedFiles = append(report.GeneratedFiles, rel)
	report.TotalGeneratedCount++
	category := strings.ToLower(dir)
	report.CategoryCounts[category] += records
	report.CategoryIDs[category] = append(report.CategoryIDs[category], ids...)
}

func copyGeneratedJSON(src, dst string) error {
	data, err := os.ReadFile(src)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(dst), 0o755); err != nil {
		return err
	}
	return os.WriteFile(dst, data, 0o644)
}

func comparableIDs(value any) []int64 {
	rows, _ := extractComparableRecords(value)
	out := make([]int64, 0, len(rows))
	for _, row := range rows {
		if id, ok := intFromAny(row["id"]); ok {
			out = append(out, int64(id))
		}
	}
	return out
}

func generateAdditionalLuaFiles(opts Options, report *Report) error {
	// Each GameCfg bundle merges thousands of Lua files under gamecfg/<name>/, so the
	// 30 bundles are built concurrently and merged back in a fixed order.
	type gameCfgWork struct{ region, sourceName, targetName string }
	var bundles []gameCfgWork
	for _, region := range supportedRegions {
		for _, name := range []string{"buff", "card", "dorm", "dungeon", "skill"} {
			bundles = append(bundles, gameCfgWork{region, name, name})
		}
		storySource := "story"
		if region == "JP" {
			storySource = "storyjp"
		}
		bundles = append(bundles, gameCfgWork{region, storySource, "story"})
	}
	bundleResults, err := runConcurrent(len(bundles), func(i int) (*gameCfgResult, error) {
		return convertReturnedGameCfg(opts, bundles[i].region, bundles[i].sourceName, bundles[i].targetName)
	})
	if err != nil {
		return err
	}
	for _, res := range bundleResults {
		if res == nil {
			continue
		}
		recordGameCfgOutput(report, res)
	}
	for _, item := range []struct{ source, target string }{
		{"JP/sharecfg/battlenodescfg.lua", "JP/ShareCfg/battle_nodes_cfg.json"},
		{"JP/sharecfg/dorm3d_dolly.lua", "JP/ShareCfg/dorm3_d_dolly.json"},
		{"JP/sharecfg/informcfg.lua", "JP/ShareCfg/inform_cfg.json"},
		{"JP/sharecfg/informforbackyardthemetemplatecfg.lua", "JP/ShareCfg/inform_for_back_yard_theme_template_cfg.json"},
		{"JP/sharecfg/world_slgbuff_data.lua", "JP/ShareCfg/world_sl_gbuff_data.json"},
	} {
		if err := generateAdditionalLuaFile(opts, report, item.source, item.target); err != nil {
			return err
		}
	}
	for _, rel := range []string{"JP/ShareCfg/enemy_data_statistics.json", "JP/ShareCfg/voice_actor_cn.json", "JP/ShareCfg/word_legal_template.json", "JP/ShareCfg/word_template.json", "JP/sharecfgdata/aircraft_template.json", "JP/sharecfgdata/enemy_data_statistics.json", "JP/sharecfgdata/equip_data_statistics.json", "JP/sharecfgdata/equip_data_template.json", "JP/sharecfgdata/weapon_property.json"} {
		if slices.Contains(report.GeneratedFiles, rel) {
			continue
		}
		luaPath := luaPathFor(opts.LuaScriptsRoot, rel)
		if _, err := os.Stat(luaPath); err != nil {
			continue
		}
		decoded, err := loadLuaFile(opts, luaPath)
		if err != nil {
			report.UnsupportedFiles = append(report.UnsupportedFiles, rel)
			continue
		}
		converted := azurlanelua.ToPlain(decoded)
		if strings.Contains(rel, "/sharecfgdata/") {
			converted = normalizeNumericTables(converted)
			converted, err = dictKeyedToSortedList(normalizeEmpty(converted))
		} else if rel == "JP/ShareCfg/voice_actor_cn.json" {
			converted, err = dictKeyedToSortedList(normalizeEmpty(converted))
		}
		if err != nil {
			report.UnsupportedFiles = append(report.UnsupportedFiles, rel)
			continue
		}
		if err := writeJSON(filepath.Join(opts.OutputRoot, filepath.FromSlash(rel)), converted); err != nil {
			return err
		}
		report.GeneratedFiles = append(report.GeneratedFiles, rel)
		report.TotalGeneratedCount++
	}
	for _, rel := range []string{"JP/buff_cfg.json", "JP/skill_cfg.json"} {
		if err := writeJSON(filepath.Join(opts.OutputRoot, filepath.FromSlash(rel)), []any{}); err != nil {
			return err
		}
		report.GeneratedHelperFiles = append(report.GeneratedHelperFiles, rel)
	}
	sortStrings(report.GeneratedFiles)
	sortStrings(report.GeneratedHelperFiles)
	return nil
}

// gameCfgResult is one GameCfg bundle's contribution to the report, produced without
// touching shared state so bundles can be built concurrently.
type gameCfgResult struct {
	rel         string
	unsupported bool
}

func generateReturnedGameCfg(opts Options, report *Report, region, sourceName, targetName string) error {
	res, err := convertReturnedGameCfg(opts, region, sourceName, targetName)
	if err != nil || res == nil {
		return err
	}
	recordGameCfgOutput(report, res)
	return nil
}

func recordGameCfgOutput(report *Report, res *gameCfgResult) {
	if res.unsupported {
		report.UnsupportedFiles = append(report.UnsupportedFiles, res.rel)
		return
	}
	report.GeneratedFiles = append(report.GeneratedFiles, res.rel)
	report.TotalGeneratedCount++
}

func convertReturnedGameCfg(opts Options, region, sourceName, targetName string) (*gameCfgResult, error) {
	pattern := filepath.Join(opts.LuaScriptsRoot, region, "gamecfg", sourceName, "*.lua")
	paths, err := filepath.Glob(pattern)
	if err != nil {
		return nil, err
	}
	if len(paths) == 0 {
		return nil, nil
	}
	sort.Strings(paths)
	merged := azurlanelua.OrderedObject{Values: map[string]any{}}
	for _, path := range paths {
		stem := strings.TrimSuffix(filepath.Base(path), ".lua")
		value, loadErr := loadLuaFile(opts, path)
		if loadErr != nil {
			return &gameCfgResult{rel: region + "/GameCfg/" + targetName + ".json", unsupported: true}, nil
		}
		merged.Keys = append(merged.Keys, stem)
		merged.Values[stem] = gameCfgEntry(value)
	}
	rel := region + "/GameCfg/" + targetName + ".json"
	if err := writeJSON(filepath.Join(opts.OutputRoot, filepath.FromSlash(rel)), merged); err != nil {
		return nil, err
	}
	return &gameCfgResult{rel: rel}, nil
}

// gameCfgEntry converts one GameCfg Lua file's value, storing an empty table as
// null. ToPlain walks the whole value, so it runs once and the result is reused.
func gameCfgEntry(value any) any {
	plain := azurlanelua.ToPlain(value)
	if list, ok := plain.([]any); ok && len(list) == 0 {
		return nil
	}
	return plain
}

func decodeOrderedJSON(data []byte) (any, error) {
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.UseNumber()
	return decodeOrderedJSONValue(decoder)
}

func decodeOrderedJSONValue(decoder *json.Decoder) (any, error) {
	token, err := decoder.Token()
	if err != nil {
		return nil, err
	}
	switch value := token.(type) {
	case json.Delim:
		if value == '{' {
			out := azurlanelua.OrderedObject{Values: map[string]any{}}
			for decoder.More() {
				keyToken, err := decoder.Token()
				if err != nil {
					return nil, err
				}
				key := keyToken.(string)
				child, err := decodeOrderedJSONValue(decoder)
				if err != nil {
					return nil, err
				}
				out.Keys = append(out.Keys, key)
				out.Values[key] = child
			}
			_, err := decoder.Token()
			return out, err
		}
		if value == '[' {
			out := []any{}
			for decoder.More() {
				child, err := decodeOrderedJSONValue(decoder)
				if err != nil {
					return nil, err
				}
				out = append(out, child)
			}
			_, err := decoder.Token()
			return out, err
		}
	}
	return token, nil
}

func luaPathFor(root, rel string) string {
	parts := strings.Split(filepath.ToSlash(rel), "/")
	if len(parts) != 3 {
		return filepath.Join(root, filepath.FromSlash(rel))
	}
	dir := strings.ToLower(parts[1])
	stem := strings.ToLower(strings.TrimSuffix(parts[2], ".json"))
	aliases := map[string]string{
		"battle_nodes_cfg": "battlenodescfg",
		"dorm3_d_dolly":    "dorm3d_dolly",
		"inform_cfg":       "informcfg",
		"inform_for_back_yard_theme_template_cfg": "informforbackyardthemetemplatecfg",
		"world_sl_gbuff_data":                     "world_slgbuff_data",
	}
	if alias, ok := aliases[stem]; ok {
		stem = alias
	}
	return filepath.Join(root, parts[0], dir, stem+".lua")
}

func streamBackingPath(root, region, dir, name string, value any) (string, error) {
	if dir != "sharecfg" {
		return "", nil
	}
	object, ok := value.(map[string]any)
	if !ok {
		return "", nil
	}
	streamed, ok := object["__stream__"].(bool)
	if !ok || !streamed {
		return "", nil
	}
	path := filepath.Join(root, region, "sharecfgdata", name)
	if _, err := os.Stat(path); err != nil {
		return "", fmt.Errorf("stream backing data for %s/%s/%s: %w", region, dir, name, err)
	}
	return path, nil
}

func globalVersionsPath() string {
	return filepath.ToSlash(filepath.Join(globalDir, "versions.json"))
}

func normalizeEmpty(v any) any {
	switch typed := v.(type) {
	case map[string]any:
		if len(typed) == 0 {
			return []any{}
		}
		out := make(map[string]any, len(typed))
		for key, value := range typed {
			out[key] = normalizeEmpty(value)
		}
		return out
	case []any:
		out := make([]any, len(typed))
		for i, value := range typed {
			out[i] = normalizeEmpty(value)
		}
		return out
	default:
		return v
	}
}

func normalizeNumericTables(v any) any {
	switch typed := v.(type) {
	case []any:
		out := make([]any, len(typed))
		for i, value := range typed {
			out[i] = normalizeNumericTables(value)
		}
		return out
	case map[string]any:
		out := make(map[string]any, len(typed))
		max := 0
		allNumeric := len(typed) > 0
		for key := range typed {
			n, err := strconv.Atoi(key)
			if err != nil || n < 1 {
				allNumeric = false
				break
			}
			if n > max {
				max = n
			}
		}
		if allNumeric && max == len(typed) {
			arr := make([]any, max)
			for i := 1; i <= max; i++ {
				value, ok := typed[strconv.Itoa(i)]
				if !ok {
					allNumeric = false
					break
				}
				arr[i-1] = normalizeNumericTables(value)
			}
			if allNumeric {
				return arr
			}
		}
		for key, value := range typed {
			out[key] = normalizeNumericTables(value)
		}
		return out
	default:
		return v
	}
}

func dictKeyedToSortedList(v any) (any, error) {
	if arr, ok := v.([]any); ok {
		out := make([]any, len(arr))
		for i, raw := range arr {
			val, ok := raw.(map[string]any)
			if !ok {
				out[i] = raw
				continue
			}
			if _, exists := val["id"]; !exists {
				cloned := make(map[string]any, len(val)+1)
				for key, child := range val {
					cloned[key] = child
				}
				cloned["id"] = generatedID(i + 1)
				val = cloned
			}
			out[i] = val
		}
		return out, nil
	}
	obj, ok := v.(map[string]any)
	if !ok {
		return v, nil
	}
	type pair struct {
		key string
		id  int
		val map[string]any
	}
	pairs := make([]pair, 0, len(obj))
	for key, raw := range obj {
		if _, err := strconv.Atoi(key); err != nil {
			continue
		}
		val, ok := raw.(map[string]any)
		if !ok {
			return v, nil
		}
		if _, ok := intFromAny(val["id"]); !ok {
			cloned := make(map[string]any, len(val)+1)
			for k, v := range val {
				cloned[k] = v
			}
			val = cloned
			val["id"] = generatedID(mustInt(key))
		}
		id, ok := intFromAny(val["id"])
		if !ok {
			return v, nil
		}
		pairs = append(pairs, pair{key: key, id: id, val: val})
	}
	if len(pairs) == 0 {
		return v, nil
	}
	slices.SortFunc(pairs, func(a, b pair) int {
		if a.id < b.id {
			return -1
		}
		if a.id > b.id {
			return 1
		}
		return strings.Compare(a.key, b.key)
	})
	out := make([]any, 0, len(pairs))
	for _, pair := range pairs {
		out = append(out, pair.val)
	}
	return out, nil
}

func recordCount(v any) int {
	switch typed := v.(type) {
	case []any:
		return len(typed)
	case map[string]any:
		return len(typed)
	default:
		return 0
	}
}

func intFromAny(v any) (int, bool) {
	switch typed := v.(type) {
	case float64:
		return int(typed), true
	case json.Number:
		n, err := strconv.ParseFloat(string(typed), 64)
		return int(n), err == nil
	case int:
		return typed, true
	case generatedID:
		return int(typed), true
	default:
		return 0, false
	}
}

func mustInt(value string) int {
	n, _ := strconv.Atoi(value)
	return n
}

func writeJSON(path string, v any) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	data, err := marshalGeneratedJSON(v)
	if err != nil {
		return err
	}
	if strings.HasSuffix(filepath.ToSlash(path), "/error_message.json") {
		var canonical any
		if err := json.Unmarshal(data, &canonical); err != nil {
			return err
		}
		data, err = json.Marshal(canonical)
		if err != nil {
			return err
		}
	}
	data = append(data, '\r', '\n')
	return os.WriteFile(path, data, 0o644)
}

func mayBeNumericKey(key string) bool {
	if key == "" {
		return false
	}
	c := key[0]
	return c == '-' || c == '+' || (c >= '0' && c <= '9')
}

func marshalGeneratedJSON(v any) ([]byte, error) {
	var enc generatedJSONEncoder
	return enc.append(nil, v)
}

// generatedJSONEncoder appends every value to one output slice instead of
// building a buffer per nested map, list and leaf and copying it into its parent.
// Leaves without a fast path share one json.Encoder and scratch buffer.
type generatedJSONEncoder struct {
	scratch bytes.Buffer
	leaf    *json.Encoder
}

// plainJSONString reports whether s encodes as itself between quotes: printable
// ASCII without a quote or backslash, and, when escapeHTML is set (map keys go
// through json.Marshal), without <, > or &.
func plainJSONString(s string, escapeHTML bool) bool {
	for i := 0; i < len(s); i++ {
		c := s[i]
		if c < 0x20 || c > 0x7e || c == '"' || c == '\\' {
			return false
		}
		if escapeHTML && (c == '<' || c == '>' || c == '&') {
			return false
		}
	}
	return true
}

func appendGeneratedJSONKey(dst []byte, key string) []byte {
	if plainJSONString(key, true) {
		dst = append(dst, '"')
		dst = append(dst, key...)
		return append(dst, '"')
	}
	kb, _ := json.Marshal(key)
	return append(dst, kb...)
}

func (e *generatedJSONEncoder) append(dst []byte, v any) ([]byte, error) {
	var err error
	switch value := v.(type) {
	case azurlanelua.OrderedObject:
		dst = append(dst, '{')
		for i, key := range value.Keys {
			if i > 0 {
				dst = append(dst, ',')
			}
			dst = appendGeneratedJSONKey(dst, key)
			dst = append(dst, ':')
			if dst, err = e.append(dst, value.Values[key]); err != nil {
				return nil, err
			}
		}
		return append(dst, '}'), nil
	case json.RawMessage:
		// Already generated output, reused verbatim (see refreshGameCfgBundle).
		return append(dst, value...), nil
	case map[string]any:
		keys := make([]string, 0, len(value))
		for key := range value {
			keys = append(keys, key)
		}
		numeric := true
		nums := make(map[string]int, len(keys))
		for _, key := range keys {
			// Most keys are field names, and strconv.Atoi allocates a *NumError for
			// every one of them. Reject the obvious non-numbers by their first byte
			// first: anything Atoi accepts starts with a sign or a digit.
			if !mayBeNumericKey(key) {
				numeric = false
				break
			}
			n, err := strconv.Atoi(key)
			if err != nil {
				numeric = false
				break
			}
			nums[key] = n
		}
		generatedIDAtEnd := false
		if _, ok := value["id"].(generatedID); ok {
			generatedIDAtEnd = true
		}
		if generatedIDAtEnd {
			sort.Slice(keys, func(i, j int) bool {
				if keys[i] == "id" {
					return false
				}
				if keys[j] == "id" {
					return true
				}
				return keys[i] < keys[j]
			})
		} else if numeric {
			sort.Slice(keys, func(i, j int) bool {
				if nums[keys[i]] != nums[keys[j]] {
					return nums[keys[i]] < nums[keys[j]]
				}
				return keys[i] < keys[j]
			})
		} else {
			// Classify once instead of inside the comparator: sort.Slice runs
			// O(n log n) comparisons and each failed Atoi allocates a *NumError.
			parsed := make(map[string]int, len(keys))
			for _, key := range keys {
				if !mayBeNumericKey(key) {
					continue
				}
				if n, err := strconv.Atoi(key); err == nil {
					parsed[key] = n
				}
			}
			sort.Slice(keys, func(i, j int) bool {
				numI, okI := parsed[keys[i]]
				numJ, okJ := parsed[keys[j]]
				if okI && okJ {
					return numI < numJ
				}
				if okI != okJ {
					return okI
				}
				return keys[i] < keys[j]
			})
		}
		dst = append(dst, '{')
		for i, key := range keys {
			if i > 0 {
				dst = append(dst, ',')
			}
			dst = appendGeneratedJSONKey(dst, key)
			dst = append(dst, ':')
			if dst, err = e.append(dst, value[key]); err != nil {
				return nil, err
			}
		}
		return append(dst, '}'), nil
	case []any:
		dst = append(dst, '[')
		for i, childValue := range value {
			if i > 0 {
				dst = append(dst, ',')
			}
			if dst, err = e.append(dst, childValue); err != nil {
				return nil, err
			}
		}
		return append(dst, ']'), nil
	case json.Number:
		if value == "-0" || value == "-0.0" {
			return append(dst, '0'), nil
		}
		parsed, err := strconv.ParseFloat(string(value), 64)
		if err == nil && math.Trunc(parsed) == parsed {
			return strconv.AppendFloat(dst, parsed, 'f', -1, 64), nil
		}
		return append(dst, value...), nil
	case generatedID:
		return strconv.AppendInt(dst, int64(value), 10), nil
	case string:
		if plainJSONString(value, false) {
			dst = append(dst, '"')
			dst = append(dst, value...)
			return append(dst, '"'), nil
		}
	}
	if e.leaf == nil {
		e.leaf = json.NewEncoder(&e.scratch)
		e.leaf.SetEscapeHTML(false)
	}
	e.scratch.Reset()
	if err := e.leaf.Encode(v); err != nil {
		return nil, err
	}
	return append(dst, bytes.TrimSuffix(e.scratch.Bytes(), []byte{'\n'})...), nil
}

func writeReport(opts Options, report *Report) error {
	reportPath := opts.ReportPath
	if reportPath == "" {
		reportPath = filepath.Join(opts.OutputRoot, "generation-report.json")
	}
	return writeJSON(reportPath, report)
}

func sortStrings(values []string) {
	slices.Sort(values)
}

func extractComparableRecords(v any) ([]map[string]any, bool) {
	switch typed := v.(type) {
	case []any:
		return recordsFromAnyItems(typed)
	case map[string]any:
		items := make([]any, 0, len(typed))
		for key, value := range typed {
			if key == "all" || key == "get_id_list_by_type" {
				continue
			}
			items = append(items, value)
		}
		return recordsFromAnyItems(items)
	default:
		return nil, false
	}
}

func recordsFromAnyItems(items []any) ([]map[string]any, bool) {
	records := make([]map[string]any, 0, len(items))
	for _, item := range items {
		switch typed := item.(type) {
		case map[string]any:
			if _, ok := intFromAny(typed["id"]); !ok {
				continue
			}
			records = append(records, typed)
		case []any:
			for _, nested := range typed {
				rec, ok := nested.(map[string]any)
				if !ok {
					return nil, false
				}
				if _, ok := intFromAny(rec["id"]); !ok {
					return nil, false
				}
				records = append(records, rec)
			}
		default:
			continue
		}
	}
	if len(records) == 0 {
		return nil, false
	}
	return records, true
}
