name: Validate data

on:
  workflow_dispatch:
  push:
    branches: [main]
  schedule:
    - cron: "0 21 * * *"

permissions:
  contents: read

jobs:
  validate:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          repository: AzurLaneTools/AzurLaneData
          ref: main
          path: _external/AzurLaneData
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            CN/**
            EN/**
            JP/**
            KR/**
            TW/**
            versions/**

      - uses: actions/checkout@v4
        with:
          repository: AzurLaneTools/AzurLaneLuaScripts
          ref: main
          path: _external/AzurLaneLuaScripts
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            versions/CN.txt
            versions/EN.txt
            versions/JP.txt
            versions/KR.txt
            versions/TW.txt

      - uses: actions/checkout@v4
        with:
          repository: ggmolly/belfast-data
          path: _external/belfast-data

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - shell: pwsh
        run: tools/ci/validate.ps1

      - uses: actions/upload-artifact@v4
        with:
          name: amagi-belfast-json-mvp
          path: ${{ runner.temp }}\amagi_belfast_json_mvp
